### PR TITLE
Make list for LAN devices dynamic

### PR DESCRIPTION
**Pull request by mhoek2**

### CODE REVIEW

**Review by nidunc — APPROVED** [review]
Seems to work fine, so LGTM.

Just an idea: perhaps we could dynamically get the computer’s hostname when `devices.cfg` does not exist, instead of calling it `example` (or a similar hard-coded value)? With `socket.gethostname()` or `socket.getfqdn()`, for example.[^1]

[^1]: https://stackoverflow.com/a/4271755

**Comment by mhoek2** [comment]
You mean to add the current device instead of an example device?

**Comment by nidunc** [comment]
> You mean to add the current device instead of an example device?

Basically, yeah, but I suppose it doesn’t matter either way, assuming that `devices.cfg` will always be present.

**Comment by mhoek2** [comment]
Maybe the, idea was when it isnt present it will a example device, so users know the format

**Comment by nidunc** [comment]
> Maybe the, idea was when it isnt present it will add a example device, so users know the format

Clear, then I suggest we leave it and merge the pull request as it is.

**Comment by mhoek2** [comment]
I added it anyway :) hehe

**Pull request merged**
