### PR TITLE
Add option to use Pathlib to create PDF files and link buttons

### PR DESCRIPTION
**Pull request by mhoek2**

### CODE REVIEW

**Review by nidunc — COMMENTED** [review]
This is how I rewrote that part myself (the main difference being that I did not include the `if` statement that you did): ```python
        files = self.read_write.getTextFiles()
        for file in files:
            # Initialize PDF
            pdf = FPDF()
            pdf.set_auto_page_break(auto=True, margin=15)
            pdf.add_page()
            pdf.set_font("Courier", size=12)

            pdf.multi_cell(0, 10, text=file["contents"].decode())

            output_filename = file['filename'].replace("txt", "pdf")
            
            output = pdf.output(dest="S").encode("latin1")
            
            self.context.read_write.writePdfFile(output_filename, output)```

It does not seem necessary to cast to a `bytearray`; Path’s `write_bytes()` also seems to accept a variable of type `bytes` (which is what fpdf’s `output(dest="S").encode("latin1")` outputs by default).

**Review by nidunc — COMMENTED** [review]
> I see, I assume you created a function like this in read_write.py?
> 
> ```python
> def writePdfFile( self, file_name: str, contents: bytes ):
>     """Write a pdf file."""
>     path = self.pdfDir.joinpath( file_name )
>     
>     path.parent.mkdir(parents=True, exist_ok=True)
>     
>     path.write_bytes(contents)   
>  ``` 

Yep, that’s pretty much the function I created.

**Comment by nidunc** [comment]
@mhoek2 I added two commits, could you quickly review them before I merge the pull request?

**Comment by mhoek2** [comment]
@nidunc  Yep looks good

**Review by nidunc — APPROVED** [review]

**Pull request merged**
