### PR TITLE
Use read_bytes instead of read_text allowing all files to be parsed

### PR DESCRIPTION
**Pull request by mhoek2**
This will allow to read from all files, perhaps .decode() has to be called in other places eventually

### CODE REVIEW

**Comment by nidunc** [comment]
What is the purpose of this PR? Is it related to (files created by) the encryption/decryption process?

**Comment by mhoek2** [comment]
> What is the purpose of this PR? Is it related to (files created by) the encryption/decryption process?

No, PDF files need to be read as bytes the application will crash when using read_text.

**Comment by nidunc** [comment]
> > What is the purpose of this PR? Is it related to (files created by) the encryption/decryption process?
> 
> No, PDF files need to be read as bytes the application will crash when using read_text.

Ah, for transferring the PDF files over the network, right? Gotcha.

**Comment by mhoek2** [comment]
It is possible that the .decode() is also required [here](https://github.com/mhoek2/tcp-share/blob/master/modules/tcp.py#L58) 

```python
                        filename = file['filename']
                        content = file['contents']
                        self.context.read_write.writeTextFile(filename, content)
```

**Review by nidunc — COMMENTED** [review]
> EDIT: I believe I was mistaken, and this change does not affect receiving files

Receiving files does indeed still seem to work the same.

I was also a bit worried that the View files screen would not work anymore, as the `ScrolledText` is now being passed bytes instead of a string (https://github.com/mhoek2/tcp-share/blob/71431fac8262b5f11e87534d86584909a1894a95/modules/gui/view_files.py#L16), but it seems like `ScrolledText` handles bytes just as well, so I think this PR is ready to be merged.

**Review by nidunc — APPROVED** [review]

**Pull request merged**
